version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
jobs:
  lint:
    docker:
      - image: cimg/python:3.8.4
    working_directory: ~/project-ml-microservice-kubernetes
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: create virtualenv
          command: |
            make setup
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            source ~/.devops/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run install
          command: |
            source ~/.devops/bin/activate
            make install
      - run:
          name: run tests
          command: |
            source ~/.devops/bin/activate
            make test
      - run:
          name: run lint
          command: |
            source ~/.devops/bin/activate
            make lint
  build:
    docker:
      - image: cimg/python:3.8.4
    working_directory: ~/project-ml-microservice-kubernetes
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
      - docker/build:
          image: ntheanh201
          tag: ml_microservice
      - run:
          name: Push Docker Image
          command: |
            docker push ntheanh201/ml_microservice
workflows:
  ci:
    jobs:
      - lint
      - build:
          context:
            - udacity_aws
          requires:
            - lint
